---
- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    source: pull

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "3000:80"
    restart_policy: always

